# Data Preparation

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load the Data
data = '../data/external/final_scout_not_dummy.csv'
df = pd.read_csv(data)
df.head()

,make_model,body_type,price,vat,km,Type,Fuel,Gears,Comfort_Convenience,Entertainment_Media,...,Previous_Owners,hp_kW,Inspection_new,Paint_Type,Upholstery_type,Gearing_Type,Displacement_cc,Weight_kg,Drive_chain,cons_comb
0,Audi A1,Sedans,15770,VAT deductible,56013.0,Used,Diesel,7.0,"Air conditioning,Armrest,Automatic climate con...","Bluetooth,Hands-free equipment,On-board comput...",...,2.0,66.0,1,Metallic,Cloth,Automatic,1422.0,1220.0,front,3.8
1,Audi A1,Sedans,14500,Price negotiable,80000.0,Used,Benzine,7.0,"Air conditioning,Automatic climate control,Hil...","Bluetooth,Hands-free equipment,On-board comput...",...,1.0,141.0,0,Metallic,Cloth,Automatic,1798.0,1255.0,front,5.6
2,Audi A1,Sedans,14640,VAT deductible,83450.0,Used,Diesel,7.0,"Air conditioning,Cruise control,Electrical sid...","MP3,On-board computer",...,1.0,85.0,0,Metallic,Cloth,Automatic,1598.0,1135.0,front,3.8
3,Audi A1,Sedans,14500,VAT deductible,73000.0,Used,Diesel,6.0,"Air suspension,Armrest,Auxiliary heating,Elect...","Bluetooth,CD player,Hands-free equipment,MP3,O...",...,1.0,66.0,0,Metallic,Cloth,Automatic,1422.0,1195.0,front,3.8
4,Audi A1,Sedans,16790,VAT deductible,16200.0,Used,Diesel,7.0,"Air conditioning,Armrest,Automatic climate con...","Bluetooth,CD player,Hands-free equipment,MP3,O...",...,1.0,66.0,1,Metallic,Cloth,Automatic,1422.0,1135.0,front,4.1

In [3]:
# Removing duplicates
df = df.drop_duplicates()
df[df.duplicated()].sum()

make_model               0
body_type                0
price                    0
vat                      0
km                     0.0
Type                     0
Fuel                     0
Gears                  0.0
Comfort_Convenience      0
Entertainment_Media      0
Extras                   0
Safety_Security          0
age                    0.0
Previous_Owners        0.0
hp_kW                  0.0
Inspection_new           0
Paint_Type               0
Upholstery_type          0
Gearing_Type             0
Displacement_cc        0.0
Weight_kg              0.0
Drive_chain              0
cons_comb              0.0
dtype: object

In [4]:
# Remove missing values
df = df.dropna()
df.isna().sum()

make_model             0
body_type              0
price                  0
vat                    0
km                     0
Type                   0
Fuel                   0
Gears                  0
Comfort_Convenience    0
Entertainment_Media    0
Extras                 0
Safety_Security        0
age                    0
Previous_Owners        0
hp_kW                  0
Inspection_new         0
Paint_Type             0
Upholstery_type        0
Gearing_Type           0
Displacement_cc        0
Weight_kg              0
Drive_chain            0
cons_comb              0
dtype: int64

In [5]:
# Format all text - removing spaces and hyphens.
df.columns = df.columns.str.lower().str.replace(' ', '_')
categorical = df.select_dtypes(include='object').columns.tolist()
for c in categorical:
    df[c] = df[c].str.lower().str.replace(' ', '_').replace('-', '_', regex=True)

In [6]:
# Format all numerical values
numerical = df.select_dtypes('number').columns.tolist()
for n in numerical:
    df[n] = pd.to_numeric(df[n], errors='coerce')

In [7]:
# Convert multi-label columns from strings to lists
multi_label = [
    'comfort_convenience',
    'entertainment_media',
    'extras',
    'safety_security']

for col in multi_label:
    df[col] = df[col].str.split(',')

In [8]:
# Seperate categorical columns from multi-label columns 
categorical = list(set(categorical)-set(multi_label))

categorical, numerical, multi_label

(['drive_chain',
  'make_model',
  'body_type',
  'upholstery_type',
  'vat',
  'fuel',
  'paint_type',
  'gearing_type',
  'type'],
 ['price',
  'km',
  'gears',
  'age',
  'previous_owners',
  'hp_kw',
  'inspection_new',
  'displacement_cc',
  'weight_kg',
  'cons_comb'],
 ['comfort_convenience', 'entertainment_media', 'extras', 'safety_security'])

In [9]:
df.head()

,make_model,body_type,price,vat,km,type,fuel,gears,comfort_convenience,entertainment_media,...,previous_owners,hp_kw,inspection_new,paint_type,upholstery_type,gearing_type,displacement_cc,weight_kg,drive_chain,cons_comb
0,audi_a1,sedans,15770,vat_deductible,56013.0,used,diesel,7.0,"[air_conditioning, armrest, automatic_climate_...","[bluetooth, hands_free_equipment, on_board_com...",...,2.0,66.0,1,metallic,cloth,automatic,1422.0,1220.0,front,3.8
1,audi_a1,sedans,14500,price_negotiable,80000.0,used,benzine,7.0,"[air_conditioning, automatic_climate_control, ...","[bluetooth, hands_free_equipment, on_board_com...",...,1.0,141.0,0,metallic,cloth,automatic,1798.0,1255.0,front,5.6
2,audi_a1,sedans,14640,vat_deductible,83450.0,used,diesel,7.0,"[air_conditioning, cruise_control, electrical_...","[mp3, on_board_computer]",...,1.0,85.0,0,metallic,cloth,automatic,1598.0,1135.0,front,3.8
3,audi_a1,sedans,14500,vat_deductible,73000.0,used,diesel,6.0,"[air_suspension, armrest, auxiliary_heating, e...","[bluetooth, cd_player, hands_free_equipment, m...",...,1.0,66.0,0,metallic,cloth,automatic,1422.0,1195.0,front,3.8
4,audi_a1,sedans,16790,vat_deductible,16200.0,used,diesel,7.0,"[air_conditioning, armrest, automatic_climate_...","[bluetooth, cd_player, hands_free_equipment, m...",...,1.0,66.0,1,metallic,cloth,automatic,1422.0,1135.0,front,4.1

## Target Variable

Note: For data integrity, the target variable will be dealt with when training the the models.

In [10]:
# The Target Variable
# target = 'price'
# Preparing the target Variable:
# y_full is a df of the Target Variable
# y_full = df[target]

# Remove Target from datase and column list
# numerical.remove(target)
# X_full = df.drop(columns=target)

In [ ]:
'''def remove_outliers(df):
    # Removing Outliers
    # Inter Quartile Range
    # Calculate the upper and lower limits
    Q1 = df[target].quantile(0.25)
    Q3 = df[target].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR

    # Create arrays of Boolean values indicating the outlier rows
    upper_array = np.where(df[target] >= upper)[0]
    lower_array = np.where(df[target] <= lower)[0]

    # Removing the outliers
    df.drop(index=upper_array, inplace=True)
    df.drop(index=lower_array, inplace=True)
    return df
'''

In [ ]:
# df = remove_outliers(df)

In [11]:
# Remove highly correlated variable from dataset and column list.
# high_corr = ['hp_kw'] 
# for h in high_corr:
#    numerical.remove(h)
# X_full = X_full.drop(columns=high_corr)

## Splitting the dataset

In [12]:
from sklearn.model_selection import train_test_split

# Split the dataframe into 60%, 20%, 20% parts
# Create Training, Validation and Testing datasets.

df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

## Saving Datasets

In [13]:
# Saving datasets
train_dfs = [
    (df_full_train, 'df_full_train'), 
    (df_train, 'df_train'),
    (df_val, 'df_val')
]
test_dfs = [
    (df_test, 'df_test')
    ]

train_dir = '../data/raw/train'
test_dir = '../data/raw/test'

for df, df_name in train_dfs:
    df.to_csv(f'{train_dir}/{df_name}.csv', index=False)
    
for df, df_name in test_dfs:
    df.to_csv(f'{test_dir}/{df_name}.csv', index=False)